package com.cherno.mazouzi.common;

import javax.annotation.CheckForNull;
import java.util.Arrays;

public class Objects {

    private Objects() {
    }

    /**
     * Determines wether two possibly-null objects are equal.
     * This should be treated as deprecated; use java.util.Objects#equals() instead.
     */
    public static boolean equals(Object a, Object b) {
        return a == b || (a != null && a.equals(b));
    }

    /**
     * Generates a hash code for multiple values. The hash code is generated by calling {@link
     * Arrays#hashCode(Object[])}. Note that array arguments to this method, with the exception of a
     * single Object array, do not get any special handling; their hash codes are based on identity
     * and not contents.
     *
     *  This method should be treated as deprecated; use {@link
     *    * java.util.Objects#hash} instead.
     */
    public static int hashcode(Object... objects) {
        return Arrays.hashCode(objects);
    }
}
